version: '3.8'

services:
  app:
    build: .
    container_name: ci4_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks: # <-- TAMBAHKAN INI
      - ci4_network

  db:
    image: postgres:15
    container_name: ci4_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: # <-- TAMBAHKAN INI
      - ci4_network

volumes:
  pgdata:

networks: # <-- TAMBAHKAN INI (SELURUH BAGIAN INI)
  ci4_network:
    driver: bridge